name: Build aiyatsbus Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 设置Java环境
      - name: Setup Java JDK
        uses: actions/setup-java@v4  # 更新到v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 安装Gradle（使用官方Gradle Action）
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3  # 官方维护的Gradle安装
        with:
          gradle-version: 8.6  # 指定Gradle版本

      # 4. 验证安装
      - name: Check versions
        run: |
          java -version
          gradle -v
          git --version

      # 5. 缓存Gradle依赖
      - name: Cache Gradle packages
        uses: actions/cache@v4  # 更新到v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6. 执行构建
      - name: Build with Gradle
        run: gradle build --no-daemon

      # 7. 存储构建产物（使用v4语法）
      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # 更新到v4
        with:
          name: aiyatsbus-plugin
          path: |
            build/libs/*.jar
            build/outputs/**/*
          retention-days: 7

      # 8. 创建发布（使用最新版本）
      - name: Create Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2  # 更新到v2
        with:
          files: |
            build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
