name: Build aiyatsbus Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 设置Java环境
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 使用Gradle Wrapper
      - name: Setup Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew --version

      # 4. 执行构建（保持简单）
      - name: Build with Gradle
        run: |
          ./gradlew clean build --no-daemon

      # 5. 查找并显示所有JAR文件（关键调试步骤）
      - name: Find all JAR files
        run: |
          echo "===== 所有JAR文件列表 ====="
          find . -name '*.jar' -print
          echo "=========================="

      # 6. 存储构建产物（使用更精确的路径）
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiyatsbus-plugin
          path: |
            plugin/build/libs/*.jar
            project/build/libs/*.jar
            project/common/build/libs/*.jar
          if-no-files-found: error
          retention-days: 7

      # 7. 创建发布
      - name: Create Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            plugin/build/libs/*.jar
            project/build/libs/*.jar
            project/common/build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
