name: Build aiyatsbus Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 设置Java环境
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 安装Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6

      # 4. 验证安装
      - name: Check versions
        run: |
          java -version
          gradle -v
          git --version

      # 5. 缓存Gradle依赖
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6. 修复Kotlin JVM目标版本问题 (关键修复)
      - name: Fix Kotlin JVM target version
        run: |
          # 设置Kotlin JVM目标版本为17
          find . -name '*.gradle.kts' -exec sed -i 's/jvmTarget = "1.8"/jvmTarget = "17"/g' {} +
          
          # 或者使用更精确的替换，如果上面的命令不起作用
          # find . -type f -name '*.gradle.kts' -exec sed -i 's/\.jvmTarget\s*=\s*["'']1.8["'']/.jvmTarget = "17"/g' {} +
          
          # 检查替换结果
          git diff || true

      # 7. 执行构建
      - name: Build with Gradle
        run: |
          # 使用Gradle Wrapper确保一致性
          chmod +x gradlew
          ./gradlew build --no-daemon --warning-mode all
          
          # 或者显式设置Kotlin JVM目标版本
          # ./gradlew build -Pkotlin.jvm.target=17 --no-daemon

      # 8. 存储构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiyatsbus-plugin
          path: |
            build/libs/*.jar
            build/outputs/**/*
          retention-days: 7

      # 9. 创建发布
      - name: Create Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
