name: Build aiyatsbus Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 设置Java环境
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 使用Gradle Wrapper
      - name: Setup Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew --version

      # 4. 修复Kotlin JVM目标版本问题（更安全的方法）
      - name: Fix Kotlin JVM target version
        run: |
          # 更安全的查找和替换方法
          find . -name '*.gradle.kts' -exec sed -i 's/jvmTarget\s*=\s*["'']1.8["'']/jvmTarget = "17"/g' {} +
          
          # 或者直接修改编译任务设置
          echo 'tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {' >> build.gradle.kts
          echo '    kotlinOptions.jvmTarget = "17"' >> build.gradle.kts
          echo '}' >> build.gradle.kts
          
          # 显示修改内容以便调试
          tail -n 5 build.gradle.kts || true

      # 5. 执行构建
      - name: Build with Gradle
        run: |
          # 使用Gradle Wrapper确保一致性
          ./gradlew clean build --no-daemon \
            -Dkotlin.compiler.jvmTarget=17 \
            -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=1g"

      # 6. 存储构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiyatsbus-plugin
          path: |
            **/build/libs/*.jar
          if-no-files-found: warn
          retention-days: 7

      # 7. 创建发布
      - name: Create Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
